<template>
<div>
    <h3 class="mb-2">Me contacter</h3>
    <v-container class="pa-0 ma-0">
        <v-card outlined class="mb-2 pa-2" style="overflow:hidden">
            <v-form>
                <v-row>
                    <v-col
                    cols="12"
                    sm="6"
                    >
                        <v-text-field
                        class="come-in"
                        :rules="nameRules"
                        label="Prénom"
                        placeholder="Rodolph"
                        outlined
                        required
                        hide-details
                        ></v-text-field>
                    </v-col>
                    <v-col
                    cols="12"
                    sm="6"
                    >
                        <v-text-field
                        class="come-in"
                        :rules="nameRules"
                        label="Nom"
                        placeholder="Jean"
                        outlined
                        required
                        hide-details
                        ></v-text-field>
                    </v-col>
                    <v-col
                    cols="12"
                    sm="12"
                    >
                        <v-text-field
                        class="come-in"
                        :rules="emailRules"
                        label="Mail"
                        placeholder="emoureton@gmail.com"
                        outlined
                        required
                        hide-details
                        ></v-text-field>
                    </v-col>
                    <v-col
                        cols="12"
                        sm="12">
                            <v-textarea
                            class="come-in"
                            outlined
                            name="Message"
                            label="Message"
                            value="The Woodman set to work at once, and so sharp was his axe that the tree was soon chopped nearly through."
                            hide-details
                            ></v-textarea>
                        </v-col>
                    <v-col>
                        <v-btn
                            color="success"
                            class="mr-4 come-in"
                            >
                            Validate
                        </v-btn>
                    </v-col>
                    
                </v-row>
            </v-form>
        </v-card>
    </v-container>
</div>
</template>